// <auto-generated />
using System;
using Forma.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Forma.Planner.PublicApi.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    partial class WriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_CI_AI")
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Forma.Domain.Entities.RoutineAggregate.Routine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Routine_OwnerId_Name");

                    b.ToTable("Routine");
                });

            modelBuilder.Entity("Forma.Domain.Entities.WorkoutAggregate.Workout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentVersionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Workout_OwnerId_Name");

                    b.ToTable("Workout");
                });

            modelBuilder.Entity("Forma.Domain.Entities.WorkoutAggregate.WorkoutVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId", "VersionNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_WorkoutVersion_WorkoutId_VersionNumber");

                    b.ToTable("WorkoutVersion");
                });

            modelBuilder.Entity("Forma.Domain.Entities.RoutineAggregate.Routine", b =>
                {
                    b.OwnsMany("Forma.Domain.Entities.RoutineAggregate.RoutineEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("RoutineId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("DayOfWeek")
                                .HasColumnType("int");

                            b1.Property<int>("Sequence")
                                .HasColumnType("int");

                            b1.Property<Guid>("WorkoutId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("RoutineId", "Id");

                            b1.ToTable("RoutineEntry", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoutineId");
                        });

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Forma.Domain.Entities.WorkoutAggregate.WorkoutVersion", b =>
                {
                    b.HasOne("Forma.Domain.Entities.WorkoutAggregate.Workout", null)
                        .WithMany("Versions")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Workout_WorkoutVersion");

                    b.OwnsMany("Forma.Domain.Entities.WorkoutAggregate.WorkoutExerciseEntry", "Entries", b1 =>
                        {
                            b1.Property<Guid>("WorkoutVersionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int?>("DurationSeconds")
                                .HasColumnType("int");

                            b1.Property<Guid>("ExerciseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("GroupId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("Reps")
                                .HasColumnType("int");

                            b1.Property<int?>("RestSeconds")
                                .HasColumnType("int");

                            b1.Property<int>("Sequence")
                                .HasColumnType("int");

                            b1.Property<int>("Sets")
                                .HasColumnType("int");

                            b1.Property<decimal?>("Weight")
                                .HasPrecision(6, 2)
                                .HasColumnType("decimal(6,2)");

                            b1.HasKey("WorkoutVersionId", "Id");

                            b1.ToTable("WorkoutExerciseEntry", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("WorkoutVersionId");
                        });

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Forma.Domain.Entities.WorkoutAggregate.Workout", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
